### ISSUE TITLE
If I have the pose sequence and coresponding 2D US sequence...

### ISSUE THREAD

**Issue by Sere1nz** [jhacsonmeza/StructuredLight_3DfreehandUS#1]
if I already had the probe pose and coresponding 2D US sequence, and I only want to reconstruct 3d ultrasound like the following figure. 
![image](https://github.com/jhacsonmeza/StructuredLight_3DfreehandUS/assets/32921181/59510f01-9cdb-4d5b-b657-dccaa2f0a5fe)

What should I do next or which sricpts should I focus on? Do I have enough reconstruction information? If not, what extra information do I need? Thank you very much!

**Comment by jhacsonmeza** [comment]
Hi @Sere1nz
You also need the transformation between the ultrasound image coordinate system and the probe coordinate system (which is the marker or target you use for the probe pose estimation). You can estimate this transformation through a calibration process. Here https://github.com/jhacsonmeza/US-Calibration you can find a repo I have for that. It's based on the calibration process using a stereo vision system and that specific marker, but you can use your own tracker and use the same [UScalib.py](https://github.com/jhacsonmeza/US-Calibration/blob/master/UScalib.py) script to do your calibration.
Once you have this transformation, you're ready to do what you want (the 3D mapping of your ultrasound slides to the 3D space). You can achieve that with [these lines of code](https://github.com/jhacsonmeza/StructuredLight_3DfreehandUS/blob/b9014e56d5012aad47ec7b4b264e88f9c38ccbe5/multimodal_recons.py#L62-L66). You just need to replace the function `mapMask` with [`mapBscans`](https://github.com/jhacsonmeza/StructuredLight_3DfreehandUS/blob/1de098de7d18ed6e6699d960793f30fcf6c6c3c9/sl_us/us3d.py#L4). The difference is that `mapMask` only maps to the 3D space the pixels inside a mask, and `mapBscans` maps the entire ultrasound slide (which is what you want).
Hope this can help. If you have any other question, please let me know!
